// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://rysnjlpwygvotktzcrqp.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InJ5c25qbHB3eWd2b3RrdHpjcnFwIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTQxMTg3MTEsImV4cCI6MjA2OTY5NDcxMX0.7d3bqSRTxoVlt5r02jhB656vJ5CDbsGIotVDpt2uWFE";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});